name: Sonar and Mobb

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Scan with SonarQube and fix with Mobb
    runs-on: ubuntu-latest
    timeout-minutes: 360

    permissions:
      pull-requests: write
      statuses: write
      contents: read
      actions: read

    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Install pip requests
        run: pip install requests

      - name: Set up JDK 23
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'temurin'
            java-version: 23
            architecture: x64
            cache: 'maven'

      - name: Check env
        run: |
          echo "Branch is: $BRANCH"
          env

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=demo-webgoat

      - name: Export SonarQube report (Push)
        if: always()
        run: |
          SONARQUBE_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          SONARQUBE_PROJECT=${{ secrets.SONAR_PROJECT_KEY }} \
          SONARQUBE_TOKEN=${{ secrets.SONAR_TOKEN }} \
          SONARQUBE_ORG="none" \
          BRANCH="$BRANCH" \
          REPORT_PATH=report.json \
          python .github/workflows/scripts/sonarqube_download_report.py

      - name: Upload SonarQube report as artifact
        if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: report.json
          retention-days: 30

      - name: Run Mobb on the findings and get fixes (PR)
        if: always() && github.event_name == 'pull_request'
        uses: mobb-dev/action/review@v1.1
        with:
          report-file: "report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scanner: sonarqube

      - name: Run Mobb on the findings and get fixes (Push)
        if: always() && github.event_name == 'push'
        uses: mobb-dev/action@v1.1
        with:
          report-file: "report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
