name: Sonar and Mobb

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Scan with SonarQube and fix with Mobb
    runs-on: ubuntu-latest
    timeout-minutes: 360

    permissions:
      pull-requests: write
      statuses: write
      contents: read
      actions: read

    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Install pip requests
        run: pip install requests

      - name: Set up JDK 23
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'temurin'
            java-version: 23
            architecture: x64
            cache: 'maven'

      - name: Check env
        run: |
          echo "Branch is: $BRANCH"
          env

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zandertek-demo-webgoat

      - name: Export SonarQube report
        if: always()
        run: |
          SONARQUBE_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          SONARQUBE_PROJECT=zandertek-demo-webgoat \
          SONARQUBE_TOKEN=${{ secrets.SONAR_TOKEN }} \
          BRANCH="$BRANCH" \
          REPORT_PATH=report.json \
          python .github/workflows/scripts/sonarqube_download_report.py

      - name: Run Mobb on the findings and get fixes
        if: always()
        uses: mobb-dev/action/review@v1.1
        with:
          report-file: "report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scanner: sonarqube
