name: Sonar and Mobb

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up JDK 23
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'temurin'
            java-version: 23
            architecture: x64
            cache: 'maven'
      # - name: Build with Maven
      #   run: mvn --no-transfer-progress verify

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zandertek-demo-webgoat
